### PR TITLE
add recommeded posts

### PR DESCRIPTION
**Pull request by huiwang**
add support on [recommended posts ](https://github.com/huiwang/hexo-recommended-posts)

### CODE REVIEW

**Comment by huiwang** [comment]
Hello @wzpan, one of my friends uses this theme in his blog and he wishes to integrate the recommended-posts plugin in his blog. So I created this PR, would you please have a look?

**Comment by huiwang** [comment]
[live preview ](http://sd44.github.io/2017/12/27/%E8%8D%89%E7%A8%BF%E4%B9%8B%E4%B8%80%E2%80%94%E2%80%94%E7%94%9F%E5%91%BD/) from my friend's blog

**Comment by wzpan** [comment]
Thanks for contributing.

Can you also add specifications on front matter settings to README? *e.g.* How to set `post_list` ?

**Comment by huiwang** [comment]
@wzpan actually, the post_list is not part of the front matter. it's a js variable holding recommended posts. sorry if it was not clear enough :)

**Comment by huiwang** [comment]
here is the doc on how the plugin works https://github.com/huiwang/hexo-recommended-posts/blob/master/README-en.md

**Comment by wzpan** [comment]
Merged. Thanks!

**Comment by huiwang** [comment]
@wzpan wow,you are amazing. Please drop me a message in case you get any issue with this plugin. Thanks very much!

**Pull request merged**
